[http]
host = "127.0.0.1"
port = 3000
proxied = true

[mysql]
host = "127.0.0.1"
username = "agentchat"
password = "hunter2"
database = "agentchat"

[chat]
charlimit = 100
agentsDir = "agents/"
maxConnectionsPerIP = 2
adminPasswordHash = "f52fbd32b2b3b86ff88ef6c490628285f482af15ddcb29541f94bcf526a3f6c7"
bannedWords = []

[chat.ratelimits]
chat = {seconds = 10, limit = 8}

[motd]
version = 1
html = """
<h2>Welcome to Agent Chat!</h2>
<h3>Rules</h3>
<ol>
    <li>Do not break US federal law or the law of the State of New Jersey</li>
    <li>Be respectful of everyone regardless of background or opinions. We have absolutely no tolerance for hate speech. Do not harass other users.</li>
    <li>Do not post anything NSFW (porn, hentai, lewd imagery, etc). The posting of Child Sexual Abuse Material will result in an immediate ban and report to the National Center for Missing and Exploited Children</li>
    <li>Do not spam in the chat and do not use bots without permission.</li>
</ol>
"""

[tts]
enabled = true
# https://git.computernewb.com/computernewb/SAPIServer
server = "http://127.0.0.1:3001"
voice = "Microsoft Sam"
tempDir = "/tmp/msac-tts"
wavExpirySeconds = 60

[[agents]]
friendlyName = "Clippy"
filename = "CLIPPIT.ACS"

[[agents]]
friendlyName = "Courtney"
filename = "courtney.acs"

[[agents]]
friendlyName = "Dot"
filename = "DOT.ACS"

[[agents]]
friendlyName = "Earl"
filename = "earl.acs"

[[agents]]
friendlyName = "F1"
filename = "F1.ACS"

[[agents]]
friendlyName = "Genie"
filename = "Genie.acs"

[[agents]]
friendlyName = "James"
filename = "James.acs"

[[agents]]
friendlyName = "Links"
filename = "Links.ACS"

[[agents]]
friendlyName = "Merlin"
filename = "merlin.acs"

[[agents]]
friendlyName = "Mother Nature"
filename = "Mother_NATURE.ACS"

[[agents]]
friendlyName = "Office Logo"
filename = "Office_Logo.ACS"

[[agents]]
friendlyName = "Peedy"
filename = "Peedy.acs"

#[[agents]]
#friendlyName = "Question"
#filename = "question_mark.acs"

[[agents]]
friendlyName = "Robby"
filename = "Robby.acs"

[[agents]]
friendlyName = "Rocky"
filename = "ROCKY.ACS"

[[agents]]
friendlyName = "Rover"
filename = "rover.acs"

[[agents]]
friendlyName = "Victor"
filename = "Victor.acs"

[[agents]]
friendlyName = "Bonzi"
filename = "Bonzi.acs"